// ============================================
// TAP TYCOON — Upgrade & Prestige-Upgrade Definitions
// ============================================

import { PrestigeUpgrade, Upgrade } from '../types';

// ---- Regular Upgrades (bought with money) ----

export const UPGRADES: readonly Upgrade[] = [
  // — Tap multipliers —
  {
    id: 'tap_2x',
    name: 'Better Fingers',
    icon: '👆',
    description: 'Tap value ×2',
    cost: 500,
    type: 'tap_multiplier',
    value: 2,
    requirement: { type: 'taps', value: 50 },
  },
  {
    id: 'tap_3x',
    name: 'Golden Touch',
    icon: '✨',
    description: 'Tap value ×3',
    cost: 25_000,
    type: 'tap_multiplier',
    value: 3,
    requirement: { type: 'taps', value: 500 },
  },
  {
    id: 'tap_5x',
    name: 'Diamond Hands',
    icon: '💎',
    description: 'Tap value ×5',
    cost: 1_000_000,
    type: 'tap_multiplier',
    value: 5,
    requirement: { type: 'taps', value: 5_000 },
  },
  {
    id: 'tap_10x',
    name: 'Midas Touch',
    icon: '👑',
    description: 'Tap value ×10',
    cost: 100_000_000,
    type: 'tap_multiplier',
    value: 10,
    requirement: { type: 'taps', value: 25_000 },
  },

  // — Business-specific multipliers —
  {
    id: 'lemon_boost',
    name: 'Organic Lemons',
    icon: '🍋',
    description: 'Lemonade Stand income ×3',
    cost: 1_000,
    type: 'business_multiplier',
    target: 'lemonade',
    value: 3,
    requirement: { type: 'business_level', target: 'lemonade', value: 10 },
  },
  {
    id: 'news_boost',
    name: 'Digital Edition',
    icon: '📱',
    description: 'Newspaper Route income ×3',
    cost: 6_000,
    type: 'business_multiplier',
    target: 'newspaper',
    value: 3,
    requirement: { type: 'business_level', target: 'newspaper', value: 10 },
  },
  {
    id: 'car_boost',
    name: 'Express Wash',
    icon: '💧',
    description: 'Car Wash income ×3',
    cost: 30_000,
    type: 'business_multiplier',
    target: 'carwash',
    value: 3,
    requirement: { type: 'business_level', target: 'carwash', value: 10 },
  },
  {
    id: 'pizza_boost',
    name: 'Secret Recipe',
    icon: '🧑‍🍳',
    description: 'Pizza Shop income ×3',
    cost: 160_000,
    type: 'business_multiplier',
    target: 'pizza',
    value: 3,
    requirement: { type: 'business_level', target: 'pizza', value: 10 },
  },
  {
    id: 'donut_boost',
    name: 'Robot Baker',
    icon: '🤖',
    description: 'Donut Factory income ×3',
    cost: 1_000_000,
    type: 'business_multiplier',
    target: 'donut',
    value: 3,
    requirement: { type: 'business_level', target: 'donut', value: 10 },
  },
  {
    id: 'shrimp_boost',
    name: 'Deep Sea Nets',
    icon: '🌊',
    description: 'Shrimp Boat income ×3',
    cost: 7_000_000,
    type: 'business_multiplier',
    target: 'shrimp',
    value: 3,
    requirement: { type: 'business_level', target: 'shrimp', value: 10 },
  },
  {
    id: 'hockey_boost',
    name: 'All-Star Team',
    icon: '⭐',
    description: 'Hockey Team income ×3',
    cost: 50_000_000,
    type: 'business_multiplier',
    target: 'hockey',
    value: 3,
    requirement: { type: 'business_level', target: 'hockey', value: 10 },
  },
  {
    id: 'movie_boost',
    name: 'CGI Studio',
    icon: '🎥',
    description: 'Movie Studio income ×3',
    cost: 400_000_000,
    type: 'business_multiplier',
    target: 'movie',
    value: 3,
    requirement: { type: 'business_level', target: 'movie', value: 10 },
  },
  {
    id: 'bank_boost',
    name: 'Crypto Division',
    icon: '₿',
    description: 'Bank income ×3',
    cost: 4_000_000_000,
    type: 'business_multiplier',
    target: 'bank',
    value: 3,
    requirement: { type: 'business_level', target: 'bank', value: 10 },
  },
  {
    id: 'oil_boost',
    name: 'Green Energy',
    icon: '⚡',
    description: 'Oil Company income ×3',
    cost: 50_000_000_000,
    type: 'business_multiplier',
    target: 'oil',
    value: 3,
    requirement: { type: 'business_level', target: 'oil', value: 10 },
  },

  // — Global multipliers —
  {
    id: 'global_2x',
    name: 'Business Degree',
    icon: '🎓',
    description: 'All income ×2',
    cost: 100_000,
    type: 'global_multiplier',
    value: 2,
    requirement: { type: 'total_earned', value: 50_000 },
  },
  {
    id: 'global_3x',
    name: 'MBA',
    icon: '📋',
    description: 'All income ×2',
    cost: 10_000_000,
    type: 'global_multiplier',
    value: 2,
    requirement: { type: 'total_earned', value: 5_000_000 },
  },
  {
    id: 'global_5x',
    name: 'CEO Mindset',
    icon: '🧠',
    description: 'All income ×3',
    cost: 5_000_000_000,
    type: 'global_multiplier',
    value: 3,
    requirement: { type: 'total_earned', value: 1_000_000_000 },
  },
];

/** Quick lookup map: upgradeId → Upgrade. */
export const UPGRADE_MAP = new Map(UPGRADES.map((u) => [u.id, u]));

// ---- Prestige Upgrades (bought with prestige points) ----

export const PRESTIGE_UPGRADES: readonly PrestigeUpgrade[] = [
  {
    id: 'p_tap_boost',
    name: 'Prestige Fingers',
    icon: '🌟',
    description: 'Tap value ×2 (permanent)',
    cost: 5,
    type: 'tap_multiplier',
    value: 2,
  },
  {
    id: 'p_income_boost',
    name: 'Prestige Empire',
    icon: '🏰',
    description: 'All income ×2 (permanent)',
    cost: 10,
    type: 'global_multiplier',
    value: 2,
  },
  {
    id: 'p_start_bonus',
    name: 'Head Start',
    icon: '🚀',
    description: 'Start with $10,000 after prestige',
    cost: 3,
    type: 'start_bonus',
    value: 10_000,
  },
  {
    id: 'p_offline_boost',
    name: 'Sweet Dreams',
    icon: '😴',
    description: 'Offline earnings ×2',
    cost: 8,
    type: 'offline_multiplier',
    value: 2,
  },
  {
    id: 'p_cost_reduce',
    name: 'Bulk Discount',
    icon: '🏷️',
    description: 'Business costs −10%',
    cost: 15,
    type: 'cost_reduction',
    value: 0.9,
  },
  {
    id: 'p_super_income',
    name: 'Money Magnet',
    icon: '🧲',
    description: 'All income ×3 (permanent)',
    cost: 50,
    type: 'global_multiplier',
    value: 3,
  },
];

export const PRESTIGE_UPGRADE_MAP = new Map(
  PRESTIGE_UPGRADES.map((u) => [u.id, u]),
);
